name: Build and deploy ASP.Net Core app to Azure Web App - sadhanaapp

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: ${{env.DOTNET_ROOT}}/myapp
          container_name: 'sadhanaappgitcode'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          # Optional: If you want to set a specific blob name
          # blob_name: 'your-blob-name'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sadhanaapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1A804A4A461147638E5C12EA540EBFE3 }}
          package: .
